Fix rare warning from calc_Huntley2006().
This example produced an innocuous warning (alongside the real error):

set.seed(1)
calc_Huntley2006(data = ExampleData.Fading$equivalentDose.data$IR50,
        rhop = c(1e-6, 1e-2),
        ddot = c(7, 0.004),
        readerDdot = c(0.134, 0.0067),
        n.MC = 10)

Error: [calc_Huntley2006()] Could not fit simulated curve, check suitability
   of model and parameters
In addition: Warning message:
In (function (..., deparse.level = 1)  :
  number of columns of result is not a multiple of vector length (arg 3)

This is a follow-up to fc80ce6, which was written with the GOK model in
mind. The EXP model has only 3 parameters, but when the simulated model
fails and the fit is attempted again fixing the D0 parameter, then there
are just 2 parameters being fixed.