use_DRAC: Remove duplication in error message.
Previously we were reporting an error message like this:

Error: [use_DRAC()] Transmission failed with error:
Couldn't resolve host name [iamnotvali8793270942hd.valid]:
Could not resolve host: iamnotvali8793270942hd.valid

See https://github.com/jeroen/curl/issues/392 for an explanation of the
cause of the duplication.